name: rtsp-simple-server-image

on:
  push:
    branches:
      - main
    tags:
      - v*.*.* # stable release like, v0.19.2
      - v*.*.*-pre.* # pre release like, v0.19.0-pre.calendardate
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Packages Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Publish dev image to container registry
      - name: Build and push rtsp-simple-server:dev image
        if: ${{ github.event_name == 'push'}}
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/rtsp-simple-server:dev

      # Publish release to container registry
      - name: populate release version
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build and push rtsp-simple-server:${{ env.RELEASE_VERSION }} image for pre release
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && contains(github.ref, '-pre.') }}
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/rtsp-simple-server:${{ env.RELEASE_VERSION }}
            ghcr.io/${{ github.repository_owner }}/rtsp-simple-server:latest

      - name: Build and push rtsp-simple-server:${{ env.RELEASE_VERSION }} image for stable release
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && (!contains(github.ref, '-pre.')) }}
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/rtsp-simple-server:${{ env.RELEASE_VERSION }}
            ghcr.io/${{ github.repository_owner }}/rtsp-simple-server:prerelease-latest
